### ISSUE TITLE
React-Native: Error on module init

### ISSUE THREAD

**Issue by dleistn1** [sindresorhus/p-cancelable#13]
In a react-native environment (0.57.5) on module import the following error is thrown and causes the app to crash: TypeError: undefined is not a function (evaluating Object.setPrototypeOf(PCancelable.prototype,Promise.prototype)')

If you change the inheritence to ES6 style (PCancelable extends Promise) the error is gone.

**Comment by sindresorhus** [comment]
That sounds like an issue with React Native. It works fine in Node.js and the browser. Open an issue on React Native instead.
