### ISSUE TITLE
Polyfill ?

### ISSUE THREAD

**Issue by fritx** [sindresorhus/p-cancelable#14]
Can this become a polyfill extends the current Promise class that I can get a cancelable Promise whenever and whereever in my app?

**Comment by sindresorhus** [comment]
No, you need to manually implement the cleanup logic, and that can only be done from inside the Promise executer. You can use [`PCancelable.fn(fn)`](https://github.com/sindresorhus/p-cancelable#pcancelablefnfn) to make it easier to make an existing promise-returning function cancelable though.
