### ISSUE TITLE
Passing cancellation reason to cancel handler

### ISSUE THREAD

**Issue by BendingBender** [sindresorhus/p-cancelable#17]
Does it make sense to pass the cancellation reason to the registered cancel handlers, like this:

```js
const promise = new PCancelable((resolve, reject, onCancel) => {
    onCancel(reason => {
        console.log(reason); // <= should print 'foo'
    });
});

promise.cancel('foo');
```

If it does, I'll make a PR.

**Comment by sindresorhus** [comment]
Do you have any use-case in mind? I don't see why not to add it, but I also don't see what it could be useful for.

**Comment by BendingBender** [comment]
Not really a use case, I just saw it was a low-hanging fruit. It kind of opens a bi-directional channel between the promise provider and consumer.

**Comment by sindresorhus** [comment]
// @bfred-it @szmarczak Thoughts?

**Comment by bfred-it** [comment]
In 2 years nobody actually needed this, so unless there's a practical use maybe it shouldn't be implemented "just in case"

**Comment by szmarczak** [comment]
I agree with @bfred-it. I don't see any use case either.
