### ISSUE TITLE
TypeScript types don't work for calling .then on a PCancelable promise

### ISSUE THREAD

**Issue by thomasjm** [sindresorhus/p-cancelable#20]
I would expect something like the following to typecheck, but it doesn't:

```typescript
let promise: PCancelable<void> = (new PCancelable((resolve, reject, onCancel) => {
  setTimeout(() => resolve());
})).then(() => console.log("Then function called"));
```

When I try to do something like this, I get the type error

```
Type 'Promise<void>' is not assignable to type 'PCancelable<void>'.
  Property 'isCanceled' is missing in type 'Promise<void>'. [2322]
```

Calling `.then` on a `PCancelable` to get a new `PCancelable` is something that should work, right? I think the reason it's not working is because the type declaration in `index.d.ts` doesn't override the `next` (or `catch`) methods when extending `Promise`:

```
declare class PCancelable<ValueType> extends Promise<ValueType> { ... }
```

**Comment by thomasjm** [comment]
CC @BendingBender as the author of the type definitions :)

**Comment by BendingBender** [comment]
@thomasjm I don't think that it works like this. Currently a plain promise is returned from `then()`/`catch()`/`finally()`.

**Comment by thomasjm** [comment]
Oh, that's unfortunate. That makes this library significantly less useful and might force me to look for a different one.

I'll close this issue then, might open a new one requesting support for this. Thanks!

**Comment by yoursunny** [comment]
I found two alternatives that allow chaining cancelable promises, but they have other problems too.

@skt-t1-byungi 's [@byungi/p-cancel](https://www.npmjs.com/package/@byungi/p-cancel) offers `pipe` function that returns a cancelable promise. However, it lacks the `onCancel.shouldReject` functionality.

@dondevi 's [promise-abortable](https://www.npmjs.com/package/promise-abortable) returns cancelable promise from `then`, `catch`, and `abort`. Its major problem is that, `abort` returns the original promise. If the original promise is rejected upon cancellation, it triggers Node "unhandled promise rejection" warning unless I write `.abort().catch(() => undefined)`, in addition to catching after the original promise.
