### ISSUE TITLE
Willing to add p-signal to the related section?

### ISSUE THREAD

**Issue by astoilkov** [sindresorhus/p-cancelable#35]
Hey @sindresorhus,

Are you willing to put my package [`p-signal`](https://github.com/astoilkov/p-signal) in the Related section?

I've already added p-cancelable in both my Alternatives and Related sections.

Thanks for the consideration!

**Comment by sindresorhus** [comment]
Sure. Pull request welcome.

Just some quick feedback. It's not immediately clear to me why I would want to use `p-signal` over using AbortController directly. I think the readme could make that clearer.

**Comment by astoilkov** [comment]
> Sure. Pull request welcome.

Cool. Thanks!

> Just some quick feedback. It's not immediately clear to me why I would want to use `p-signal` over using AbortController directly. I think the readme could make that clearer.

Aha. I guess that's because of the bad example I gave with `pSignal(signal, fetch(url))` because it's better to do `fetch(url, { signal })`? I've changed the example. Do you think that makes it clearer?

**Comment by sindresorhus** [comment]
It's still not clear to me why I would use it over plain `AbortController`. I would recommend writing it clearly in prose how it's better.

**Comment by astoilkov** [comment]
Hmm. I think I'm missing something. I can't think of an easy way to do it with `AbortController`. If there was an easy alternative, I would also struggle to see why I would use `p-signal` over `AbortController`.

This means that either, there is an easy way I don't know, or I am missing something else.

Let's take a pseudo code for example:
```ts
for (const item of items) {
  await pSignal(signal, parseText(item.text))
}
```

How this can be written using `AbortController`?

Thoughts:
- Maybe I should just say that using `AbortController` will be a lot more code.
- I know that you have a lot of experience with open-source and I'm sure you are seeing something that I don't. I would be very happy if I can understand your thinking. That may help me in the future as well.

**Comment by sindresorhus** [comment]
If we take the example in your readme. I fail to see how it's actually getting aborted. It just seems that the `await pSignal(AbortSignal.timeout(200), longRunningTask())` call does indeed get aborted, but `await parseText(currentFile.text)` will continue running in the background.

The important thing with AbortSignal is that it has to be passed down to every single method, otherwise, it will not actually do what you expect.

**Comment by sindresorhus** [comment]
> How this can be written using AbortController?

You cannot easily write exactly the same code, but that's my point. You need to clearly show what problem it solves. Say someone is used to using AbortController, they wouldn't immediately see what problem this solves for them.

**Comment by astoilkov** [comment]
Got it! I will update the readme.

 Thank you ❤️
