### ISSUE TITLE
【Discussion】Object.setPrototypeOf(PCancelable.prototype, Promise.prototype)

### ISSUE THREAD

**Issue by wfk007** [sindresorhus/p-cancelable#37]
in devdocs: https://devdocs.io/javascript/global_objects/object/setprototypeof

It warns that
> Warning: Changing the [[Prototype]] of an object is, by the nature of how modern JavaScript engines optimize property accesses, currently a very slow operation in every browser and JavaScript engine. In addition, the effects of altering inheritance are subtle and far-flung, and are not limited to the time spent in the Object.setPrototypeOf(...) statement, but may extend to any code that has access to any object whose [[Prototype]] has been altered. You can read more in [JavaScript engine fundamentals: optimizing prototypes](https://mathiasbynens.be/notes/prototypes).

I am puzzled about the usage of setPrototypeOf with `PCancelable.prototype`. whether it is a bad practice as warnned?
> I think not because it doesn't change the promise.prototype in runtime

how about the following code? we usually need to proxy the original functions and add some logic ourselves
```js
const originalCatch = Promise.prototype.catch;
Promise.prototype.catch = (reject) => {
	console.log("my catch");
	return originalCatch(reject);
};
```

**Comment by sindresorhus** [comment]
Your answer was just a 2 second `git blame` away: https://github.com/sindresorhus/p-cancelable/commit/fe1fb8ede911846b428ecd7deb8e8c895c1ca165
