### ISSUE TITLE
How to use this with p-lazy?

### ISSUE THREAD

**Issue by pastelmind** [sindresorhus/p-cancelable#50]
I want a Promise that is cancelable *and* whose executor is lazily evaluated. Is this possible by composing p-cancelable with [p-lazy](https://github.com/sindresorhus/p-lazy)?

At the moment it seems impossible. If I wrap p-lazy with p-cancelable...

```js
const cancelable = new PCancelable((outerResolve, outerReject, onCancel) => {
  const lazy = new PLazy((innerResolve, innerReject) => {
    // Our executor logic goes here
    // use innerResolve, innerReject, onCancel
  })
  lazy.then(outerResolve, outerReject) // Oops
})
```

...it would no longer be lazy, because calling `lazy.then()` triggers the executor. On the other hand, if I wrap p-cancelable with p-lazy...

```js
const lazy = new PLazy((outerResolve, outerReject) => {
  const cancelable = new PCancelable((innerResolve, innerReject, onCancel) => {
    // Our executor logic goes here
    // use innerResolve, innerReject, onCancel
  })
  cancelable.then(outerResolve, outerReject)
})
```

...then we cannot cancel it because `lazy` does not have a `.cancel()` method.

**Comment by sindresorhus** [comment]
No, they don't work with each other. In general, the community is moving towards `AbortController` (with all its flaws) instead of cancellable promises, so it may be worth adopting that instead in your code.

**Comment by pastelmind** [comment]
Thanks. I suppose I could roll my own implementation.
